### ISSUE TITLE
Feature request: roadmap and a defined architecture

### ISSUE THREAD

**Issue by AlvaroMolano** [frappe/mobile#1]
Hi, I am so glad you have started an official frappe mobile client.
I am keen to comment on business cases and do some development to help.

I see you just started development, Would it be possible for you to share a roadmap of features? Please.
It would also be nice you share what architecture will you apply and why.

Thank you

**Comment by AlvaroMolano** [comment]
In order to get help from the community, you should include a contribution guideline, like the following.
https://github.com/CoolProp/CoolProp/wiki/Contributing:-git-development-workflow

Regarding architecture, it is important to take in consideration if it is going to be appropriate for large data handling and realtime collaboration.

Regarding roadmap, I would also recommend time and location tracking plus chat in a slack style.
Please comment,

**Comment by scmmishra** [comment]
Hi @AlvaroMolano thank you very much for the feedback, the project is still at a very foundational state, we’re experimenting, making and breaking stuff. We will soon update issue templates, readme and other docs along with a comprehensive roadmap.

**Comment by AlvaroMolano** [comment]
@scmmishra Great to see you are working on this repository, that roadmap will be really helpful.
Best
