### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by SarthakBhargava** [frappe/mobile#27]
Android: 
After filling the form and pressing the login button, the app does not redirect to the application.

**Comment by sumitbhanushali** [comment]
@SarthakBhargava please make sure you are on latest develop branch since there is change in API of Frappe Framework.

**Comment by Sarthak788** [comment]
What would be the best way to change this code so that we can incorporate the new API responses.
I am new to development and want to learn how flutter and frappe works.

**Comment by sumitbhanushali** [comment]
@Sarthak788 Flutter App is already on latest code, you need to use latest develop branch of Frappe Framework to make it work.

**Comment by Sarthak788** [comment]
Thank You

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/34
