### ISSUE TITLE
Does V13 Beta.12 works?

### ISSUE THREAD

**Issue by Helkyd** [frappe/mobile#30]
Hi all,
Trying on my site (https://demo13.angolaerp.co.ao) and i can see the logs that is logged in but the app does not go beyond stays on the Login page....

Current Server Version:
**erpnext 13.0.0-beta.12
frappe 13.0.0-beta.11**

Any tips?

**Comment by sumitbhanushali** [comment]
@Helkyd you need to be on latest develop branch of Frappe Framework

**Comment by sumitbhanushali** [comment]
similar issue: https://github.com/frappe/mobile/issues/27

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/34
