### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by Sarthak788** [frappe/mobile#31]
Hello,

I am trying to use my ERPnext login on the frappe application, but it doesn't login for some reason. I have tried a lot of different things from my end but it doesn't seem to work. Any suggestions?

Thank you

**Comment by sumitbhanushali** [comment]
@Sarthak788  make sure you are on latest develop branch of Frappe Framework

**Comment by sumitbhanushali** [comment]
duplicate issue: https://github.com/frappe/mobile/issues/27

**Comment by AdityaAgarwal256** [comment]
Hello, I am experiencing the same issue. I believe I am on the latest development branch, but could you please elaborate??
Also, where can I find the develop branch??

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/34
