### ISSUE TITLE
How do I build an apk?

### ISSUE THREAD

**Issue by dawoodjee** [frappe/mobile#40]
I want to make an apk and test it on my mobile. I'm using Android studio. I just really want to test this thing I'm having trouble running it according to the instructions on the readme. Building also has issues. 

If anyone has the apk please let me know

**Comment by sumitbhanushali** [comment]
@dawoodjee 
https://discuss.erpnext.com/t/beta-frappe-mobile-built-on-flutter-android-ios/71552/49?u=sumitbhanushali
