### ISSUE TITLE
ERPNEXT Mobile App Error 404 (Mobile Application Not loading after V13 Update)

### ISSUE THREAD

**Issue by dsatsangi** [frappe/mobile#41]
## Description of the issue
ERPNEXT Mobile App Error 404 (Mobile Application Not loading after V13 Update)
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
![WhatsApp Image 2021-04-03 at 16 16 05](https://user-images.githubusercontent.com/29353492/113476524-9ecbde00-9499-11eb-8f9d-3871242fc912.jpeg)

(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by sumitbhanushali** [comment]
closing because this issue is not related to this repo
