### ISSUE TITLE
Checkbox not updating in formValue 

### ISSUE THREAD

**Issue by mohit7208** [frappe/mobile#57]
When i check a checkbox its not adding that to formValue i tried printing it and it doesnt adds that 

so it should have added selling 1 when i checked the checkbox

These are key and value of formValue

newname xyz
apply_on Item Code
items [{item_code: 1101, uom: Kg}]
item_groups null
brands null
apply_rule_on_other null
other_item_code null
other_item_group null
other_brand null
applicable_for Customer
customer M Y
customer_group null
territory null
sales_partner null
campaign null
supplier null
supplier_group null
valid_from 2021-07-24T00:00:00.000
valid_upto 2021-07-27T00:00:00.000
company Abc
currency INR
price_discount_slabs [{min_qty: 5, max_qty: 5, min_amount: 0, max_amount: 0, rate_or_discount: Rate, rate: 5}]

**Comment by mohit7208** [comment]
Hey i wanna contribute so can you guide me on how to fix that

**Comment by mohit7208** [comment]
I tried logging onChanged val in form/check.dart but it doesnt print anything

**Comment by sumitbhanushali** [comment]
way flutter_form_builder package handles fields have been changed in latest version, this was missed by me for checkbox field, thanks for digging that out.
you can refer how flutter_form_builder now handle fields and implement that change for checkbox

**Comment by mohit7208** [comment]
Hi i have created a new branch and pushed my code what should i do now shall i create a pull request

**Comment by mohit7208** [comment]
i have created a draft pull request suggest me further

**Comment by sumitbhanushali** [comment]
solved in https://github.com/frappe/mobile/pull/58
