### ISSUE TITLE
Home Page: Menu bifurcation as on web

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/mobile#63]
On web, the menu is bifurcated into "MODULES". "DOMAINS" and "ADMINISTRATION" options. This can be done on mobile as well.

Mobile View - 

![Screenshot_20210806-151243](https://user-images.githubusercontent.com/82337328/128496279-44106163-9121-4995-b1ce-635f56f60d3c.jpg)

Web View - 

![Screenshot 2021-08-06 at 3 45 11 PM](https://user-images.githubusercontent.com/82337328/128496323-bc85ba6a-daf5-4c26-a6c5-546ced3bfefd.png)

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/66
