### ISSUE TITLE
New in erpnext , need to check flutter app which rest-api url needs to be put in login screen.

### ISSUE THREAD

**Issue by ptawde95** [frappe/mobile#67]
Kindly let me know which rest-api url needs to be put in login screen.
I tried to put the URL generated by Frappe PWD.

**Comment by sumitbhanushali** [comment]
same url you would put on browser for accessing frappe app

**Comment by ptawde95** [comment]
Hi @sumitbhanushali  , i tried to put the URL generated by frappe PWD showed me the below error message

**PWD URL :** http://ip172-18-0-19-c4aandfnjsv000eg08t0-80.direct.labs.play-with-docker.com/
![Screenshot_20210812-115056](https://user-images.githubusercontent.com/47977097/129147945-b8ce42e1-8777-44fe-96e5-a199eee24b40.png)

**Comment by sumitbhanushali** [comment]
mobile app will only work on secure server i.e with https certificate

**Comment by ptawde95** [comment]
@saurabh6790  Thanks for your response .
Can I get Demo/Preview URL to check the mobile App ?
