### ISSUE TITLE
CRM sync with phone's call list and/or phone book

### ISSUE THREAD

**Issue by vinkas** [frappe/mobile#71]
This app should get connection to phones adress book and call list.
Use cases:

- Always know who is your caller an existing Lead/Contact or a potential lead;
- Transfer all calls to CRM's appropriate element (Lead, Contact or Deal).

**Comment by TurkerTunali** [comment]
Does not Google integrations support this?

**Comment by vinkas** [comment]
I suppose it can. What I would like to see is an app similar to [VTiger's](https://play.google.com/store/apps/details?id=com.vtiger.apps.vtigerlite) or [SuiteCRM](https://play.google.com/store/apps/details?id=com.magneticonemobile.phone2crm.suite). I suppose that such a powerfull Company could create such app with ease :)

**Comment by TurkerTunali** [comment]
What does VTiger or SuiteCRM do differently? I suppose with Google Contact integratin you can see new customers in your phone also.

**Comment by vinkas** [comment]
Ok now I get that. Thank you for explanation. However, will ERPNext will get information which sales manager and when made a sales call from his contacts list? How the calls data (e. g. call date, number of calls to the same lead/contact) can be transfered to CRM?

**Comment by TurkerTunali** [comment]
Good question. Good feature suggestion. I believe that there are some CRM solutions which does that. Does vTiger or SuiteCRM extracts info from the calls user made? I believe that it's phone systems job to do that.

**Comment by vinkas** [comment]
I have had this kind of solution on Bitrix, as it had telephony module. I can not say, that it was a perfect solution because of constant breakdowns and issues, but we where able to check what a manager has talked about during his/her call.

This feature is not what I want on ERPNext as it can be done more easily through third party integrations and leave ERPNext at its best - manage the CRM.

However we could have an Android/iPhone app which would send data to our ERPNext and create new leads there. That would be a very nice feature 😉
