### ISSUE TITLE
Error can't login

### ISSUE THREAD

**Issue by arrazka** [frappe/mobile#82]
Idownload and login  to self hosted erpnext.. but error login..

**Comment by sumitbhanushali** [comment]
can you provide screenshot of error?

**Comment by arrazka** [comment]
@sumitbhanushali thanks for your reply .. problem solved...

**Comment by pm-at** [comment]
I'm facing same error. 
![Screenshot_20210916-173808](https://user-images.githubusercontent.com/37295029/133610069-fb3292f7-ccdf-42c6-8acd-377a29574032.png)
