### ISSUE TITLE
"error" at login

### ISSUE THREAD

**Issue by moe01324** [frappe/mobile#87]
trying to login just puts up "error"

server-address is valid, credentials are correct.

<img src="https://user-images.githubusercontent.com/13005756/133733598-2887a0d6-212b-41ea-abc3-ef2012374978.png" width="300" >

**Comment by sumitbhanushali** [comment]
is your server running on frappe v13?

**Comment by moe01324** [comment]
> is your server running on frappe v13?

yes, self hosted on AWS with version 13.2.0
![image](https://user-images.githubusercontent.com/13005756/133739941-ff08064b-6b71-42de-97dc-a31af5b346e7.png)

**Comment by sumitbhanushali** [comment]
can you create test user and DM the test creds?

**Comment by moe01324** [comment]
could it be related to activated 2FA?

when i try with admin account (no 2FA active) i can login successfully.

**Comment by sumitbhanushali** [comment]
yes, it is happening for 2FA cases

**Comment by sumitbhanushali** [comment]
deployed fix on v1.1
