### ISSUE TITLE
LDAP Login missing

### ISSUE THREAD

**Issue by b90g** [frappe/mobile#92]
Ahoy,
if i try to login while LDAP is my main IDP, the login fails. An extra button like on the browser interface is missing, so i guess the mobile App uses the native user login.

Tested on Android & Ios with freshly installed apps.

**Comment by tbluhmitsdave** [comment]
I second this as a feature request.

**Comment by sumitbhanushali** [comment]
@tbluhmitsdave yup, this would be feature request

**Comment by b90g** [comment]
should i put this into another system? which?

**Comment by sumitbhanushali** [comment]
@b90g no, need I have added `enhancement` label. 
here is fine

**Comment by latoile** [comment]
I also support this request

**Comment by billy995** [comment]
is there something new?

**Comment by b90g** [comment]
https://discuss.erpnext.com/t/deprecating-erpnext-mobile-apps/84121 - Closing since app is going depricated. Thanks for the effort, will focus on the issue of unifying the login buttons in webview
