### ISSUE TITLE
Only work with https protocol

### ISSUE THREAD

**Issue by j209** [frappe/mobile#97]
Hi
Why frappe mobile don't support http and only work with https?

**Comment by sumitbhanushali** [comment]
support for http is on the roadmap

**Comment by saru2020** [comment]
How do I make it work with a localhost frappe app?

**Comment by sumitbhanushali** [comment]
@saru2020 you can comment out line 56,57,58 of setBaseUrl function residing in http.dart file and use ngrok to start server
https://frappeframework.com/docs/user/en/bench/frappe-commands#site-commands

**Comment by j209** [comment]
frappe mobile project is depricated
